<?php ?>
  <h3 id="credits" class="mtm">Credits</h3>
  <ul class="inline-block-list">
    <li>Credits to <a href="http://ethanschoonover.com/solarized">Ethan Schoonover</a>  whose <a href="http://github.com/altercation/solarized">Solarized colorscheme</a> was a model for these colorschemes</li>
    <li>And credits to <a href="http://chriskempson.com/">Chris Kempson</a>, whose <a href="https://github.com/chriskempson/base16-builder">Base16 Builder</a>  was used for conversion to the different output formats.</li>
  </ul>
<?php ?>
