<!doctype html><html lang="en"><meta charset="utf-8"><title><?php echo $title; ?></title>
<style id="criticalCssCustom"><?php include "critical-css-custom.inc" ?></style>
<link rel="preload" href="<?php echo $rootUrl ?>assets/css/style-redesign-v1.css" as="style" onload="this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="<?php echo $rootUrl ?>assets/css/style-redesign-v1.css"></noscript>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Bram de Haan">
  <meta name="description" content="<?php echo $description; ?>"/>
  <link rel="author" href="https://plus.google.com/+BramdeHaan/posts">
<?php ?>
